// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKHgQ-GiT3iYxnXvLLDG1eKIOOfLDKEI',
    appId: '1:596870391568:web:33a9eae1382c6b704ea795',
    messagingSenderId: '596870391568',
    projectId: 'mej-koinonia',
    authDomain: 'mej-koinonia.firebaseapp.com',
    storageBucket: 'mej-koinonia.firebasestorage.app',
    measurementId: 'G-Z5WBF47CLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8Aq1IqnGVVQiX2UR9AOOoYtnMMf7Cc4',
    appId: '1:596870391568:android:2062a736f40bb96a4ea795',
    messagingSenderId: '596870391568',
    projectId: 'mej-koinonia',
    storageBucket: 'mej-koinonia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQw3mT4mVO2azKQIyCPvqnLytLPkTvgw',
    appId: '1:596870391568:ios:8f8b7a0305a352154ea795',
    messagingSenderId: '596870391568',
    projectId: 'mej-koinonia',
    storageBucket: 'mej-koinonia.firebasestorage.app',
    iosBundleId: 'com.example.ekoinonia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQw3mT4mVO2azKQIyCPvqnLytLPkTvgw',
    appId: '1:596870391568:ios:8f8b7a0305a352154ea795',
    messagingSenderId: '596870391568',
    projectId: 'mej-koinonia',
    storageBucket: 'mej-koinonia.firebasestorage.app',
    iosBundleId: 'com.example.ekoinonia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKHgQ-GiT3iYxnXvLLDG1eKIOOfLDKEI',
    appId: '1:596870391568:web:fb66025af5e7ed0f4ea795',
    messagingSenderId: '596870391568',
    projectId: 'mej-koinonia',
    authDomain: 'mej-koinonia.firebaseapp.com',
    storageBucket: 'mej-koinonia.firebasestorage.app',
    measurementId: 'G-LPXW2NDYLY',
  );
}
